version: 2.0
jobs:
  build:
    docker:
      - image: matoba/np:12-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check 
          command: |
            npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run browser-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
