version: 2.0
jobs:
  build:
    docker:
      - image: node:20-bookworm
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check 
          command: |
            npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
